[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[fmt]
line_length = 100
bracket_spacing = true
tab_width = 2
number_underscore = "thousands"
sort_imports = true

[dependencies]
forge-std = "1.9.4"
"@uniswap-v3-periphery" = "1.4.4"
solady = "0.0.275"
"@uniswap-swap-router-contracts" = "1.3.1"
